# Generated by Django 2.0.3 on 2018-04-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_name',
            new_name='cart_product_name',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_price',
            new_name='cart_product_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_image',
        ),
    ]
