# Generated by Django 2.0.3 on 2018-04-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20180404_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info',
            new_name='user_info',
        ),
    ]
